export const GET_CONTACTS_REQUEST = 'GET_CONTACTS_REQUEST';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_ERROR = 'GET_CONTACTS_ERROR';

export const GET_CONTACTS_BY_ID_REQUEST = 'GET_CONTACTS_BY_ID_REQUEST';
export const GET_CONTACTS_BY_ID_SUCCESS = 'GET_CONTACTS_BY_ID_SUCCESS';
export const GET_CONTACTS_BY_ID_ERROR = 'GET_CONTACTS_BY_ID_ERROR';


export const CREATE_CONTACTS_REQUEST = 'CREATE_CONTACTS_REQUEST';
export const CREATE_CONTACTS_SUCCESS = 'CREATE_CONTACTS_SUCCESS';
export const CREATE_CONTACTS_ERROR = 'CREATE_CONTACTS_ERROR';

export const UPDATE_CONTACTS_REQUEST = 'UPDATE_CONTACTS_REQUEST';
export const UPDATE_CONTACTS_SUCCESS = 'UPDATE_CONTACTS_SUCCESS';
export const UPDATE_CONTACTS_ERROR = 'UPDATE_CONTACTS_ERROR';

export const DELETE_CONTACTS_REQUEST = 'DELETE_CONTACTS_REQUEST';
export const DELETE_CONTACTS_SUCCESS = 'DELETE_CONTACTS_SUCCESS';
export const DELETE_CONTACTS_ERROR = 'DELETE_CONTACTS_ERROR';
